apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-echo
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-echo
  template:
    metadata:
      labels:
        app: webhook-echo
    spec:
      containers:
        - name: webhook-echo
          image: mendhak/http-https-echo:31
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: HTTP_PORT
              value: "8080"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
