alertmanager:
  config:
    receivers:
      - name: telegram
        telegram_configs:
          - bot_token: ENC[AES256_GCM,data:R3ttdw4G4bmiY9HYCZw4rhDYBGx5uPtr1c71d062alLdGKbgJw5qzVdhZcW23w==,iv:/G+hq3/6eNHjBADMidAv3DLv3KHJ5aBZ0PGdOln6Vq4=,tag:B5aoMdmltOfkY59ImdfqoA==,type:str]
            chat_id: -1004302601848
            send_resolved: true
            message: '{{ template "telegram.lab2.text" . }}'
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aWdRNjdWZkMzVTJVT1lB
        dlZrdXhFNUcyS09iaHB5R0IrdEhQbmVnTUFrCk1maCs2YnBxM2svdkhFVms3VE96
        MTNiVis1aUJwTEM4THRPWGpIaTJlUmMKLS0tICtHQ2Z4VDJxdThyTW1OelhjdU80
        RkNRMVJpWThFbkN3ZTdjencwOHJmVFUKluJvPVuSw4GWSDuXciQAQOzxVnVJF04V
        lAzWzcvjDFjKGEqJVA3+A3BsIn5Oi6NSO5Ry9yKN+vKyDMxEp2O4zQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hzgk40srsm6xv260h0xptaa0qqdpetegx5vjl78x9qmk9u92jagsezvequ
  encrypted_regex: (?i).*token.*
  lastmodified: "2026-09-20T20:58:07Z"
  mac: ENC[AES256_GCM,data:yuIpmwLx8lRIoLWXhJ9Q1lobhh4hLBEDNF7TVt3WDxLpef4SwUrUUwobEypKXdhGXWas9D1wQtpwPkYo0vjwigMURVnE/yxOOA8udOlY5/91DFobCHxNKVy2wIp5nOJc8RdQR4ngoW7E++RmVB+aJBX07T+48iDtbeKzdmBw58k=,iv:7l0mF+wUPGaY4dCif6eqL9QqyPR8ideN6qojkzqjbv4=,tag:jBB+JdPQv+O4GimdmfxwMQ==,type:str]
  version: 3.13.3
