alertmanager:
    enabled: true
    config:
        receivers:
            - name: telegram
              telegram_configs:
                - bot_token: ENC[AES256_GCM,data:P/JEJsoiSQYyNJMjwx7OMYf2o1LPWLH+Wzs6sdQ5nEmXm5Kds9RMUL/YFq7NTQ==,iv:6L//AxX9ubPzTYXNGREFnEDraYxob2iKmnvj3BRieg8=,tag:dm/wd2URU0PbSUWxWRJ9eQ==,type:str]
                  chat_id: -1004302601848
                  send_resolved: true
        route:
            group_wait: 10s
            group_interval: 5m
            receiver: telegram
            repeat_interval: 1h
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwR1VNelN4Y2pxdVlHSzRZ
            a01kS3FXODlOQUpmYVYvVTVtdys3emZjRncwCkJWOGpSTEUrWVAzMlVRQzNLcTFk
            ZDlqM1BpVlpiWHJXT0NYMklKcGEzSEUKLS0tIHJMM3k1RE5EOUhXeExGbFNCcnpz
            RmFKb1BQalp1RnQ4RExlL3F5Mm1UcnMKpZnX5hehin4ClP0Yq/ofGCaU2s3NAP3E
            vGaDpovmirwVSmQ+ZU2AnNJFLVxEzg+iG3eY6r1TND+20bVw6S7ZLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hzgk40srsm6xv260h0xptaa0qqdpetegx5vjl78x9qmk9u92jagsezvequ
    encrypted_regex: (?i).*token.*
    lastmodified: "2026-09-20T19:59:42Z"
    mac: ENC[AES256_GCM,data:ZvNxgaynguVXRtMckNnOeZRyFDeVhEdWUkvCMkIZVlZY3wKGx7E1SOAwOXb7dC5PXYJYZ/K39ZZNQPIIqxXfb9pxpf77zhYyA0Od5yjYSvRuJco/ElWXHr3DI9MfbMwc1UD+N4z2AAgPiQ7aQZSzjCGJbMX5oMmwHN91t2Z2LPc=,iv:JV1ZlJSBIlGPDvNSJAMC14dNNTzcxL0pRO7XW9gv+gA=,tag:iHZgnKQPCK0MMdD7FMyFMg==,type:str]
    version: 3.13.3
