prometheusSecret:
  bot_token: ENC[AES256_GCM,data:Nb4HaO7EUvlqSIaa9OflJ38ideXStml4DoBJcNJvnOX8Xt8G+Op6wOAWM/rX8g==,iv:XOA0fW9eG/jwNcLdAsX5bsXflExKUJQ7tqPORGR8C8c=,tag:+1T6bIFhTt9nodHZj5iRyQ==,type:str]
  chat_id: ENC[AES256_GCM,data:bctnsl0k7e4M3Zkb5e0=,iv:rANIIjzOsmen7W/uK4qfkimS46bsuySsHYz29h/5vHg=,tag:hTEkBK++NAEEPRwRaVqHGw==,type:int]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRWFpUGNXLzFTOTlWZ1lU
        T1Q5eGNSYXBQSkVPdnR4YlJWdVFCMWNQQ1UwCkhYbWI3ckRYZk1OcGgyUTFXMXV3
        NlNsM2tqelFNazhmN0FKYnRZWlBLSk0KLS0tIGxPRjVTUy9LWnVRU1VtemIwSW9N
        bmlDQkhKdGpzTjZwUnREMWJKZzFGdk0KgeSrkNrlDHDwd2UrtD1kTtlBHf/CR6sD
        Ic59OcUnLWeBtJMe46LN778FO7vHM6ojbkBtQSbOXRhdZZYZ2DLkLg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hzgk40srsm6xv260h0xptaa0qqdpetegx5vjl78x9qmk9u92jagsezvequ
  encrypted_regex: (?i)(.*token.*|.*_id$)
  lastmodified: "2026-09-22T17:00:51Z"
  mac: ENC[AES256_GCM,data:nbkFzaOPMW0FON6mPyRgMW+2oGIE9ZcXc1W2R/SeqoUzuNmvrjH0k22JF6DEGxm04XOdY1iLV818XEIKzUEeljQIrHMG7LACvTHMBS5v7dRhkE+wGLXK1jyDUKffag0ambE+UDpy/WqGDejoyKvXd0sUm0H+4EDzSJPONaP6uQg=,iv:gKTbyjscchY2GraROFLY8/pYFV73amHKU+uW99sZ9dQ=,tag:gBkHrctoOUsyPVOTEyfj8Q==,type:str]
  version: 3.13.3
